# base image
FROM node:16

# set working directory
RUN mkdir /app && chown node:node /app
WORKDIR /app

# add app
USER node

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 4200
